image: Visual Studio 2017

install:
  - createVSProject.bat

build_script:
  - msbuild TheTube.sln

test: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false